### ISSUE TITLE
No documentation provided

### ISSUE THREAD

**Issue by BenDol** [threerings/playn#77]
I am keen on learning this tool but can't find any documentation on the wiki or on google even. Would be great to have somewhere to start.

If I have missed something just let me know! Thanks

**Comment by samskivert** [comment]
Did you notice this at the top of the README?

"Information on PlayN can be found in in this README and on the PlayN project website: http://code.google.com/p/playn"

Go to the (soon to be obsolete, but currently still the best place to get docs) Google Code website.

**Comment by samskivert** [comment]
Oh, my bad. Someone rerouted that website to here. Oops! They shouldn't have done that (yet).

Anyway, just use the new website: http://playn.io/

It's not 100% done but it's better than everything else.
