### ISSUE TITLE
Support for GIF Animations

### ISSUE THREAD

**Issue by BenDol** [threerings/playn#79]
Hey wondering if there would be a way to load a GIF image and animate it? It makes sense that this could be possible with Java, but to have this work on HTML is probably not as straight forward? Anyway appreciate any help I can get!

**Comment by BenDol** [comment]
Got my GIF files extracted and loaded as sprite sheets, but the sprites end up taking up 100mb per unique instance. Might need some help optimizing my images haha. Thanks!

**Comment by samskivert** [comment]
Yeah, this is not really something that would be implemented at the platform layer. We couldn't automatically process GIFs in the HTML backend, and it's not really worth the trouble for the other backends. Better to pre-process your GIF and do it in a library that someone (other than me) writes which works on top of PlayN.
