### ISSUE TITLE
Detecting keyboard modifiers (Shift, Alt, Ctrl, etc)

### ISSUE THREAD

**Issue by BenDol** [threerings/playn#80]
I can't find out how to detect keyboard modifier clicks, if there isn't a way to do it, perhaps it could be implemented since its a very common feature required in game design.

I would have expected the modifiers to be returned in the Keyboard.Event

Cheers!

**Comment by samskivert** [comment]
Right now PlayN does not report the up/down state of the modifier keys. You can listen for, for example, a Key pressed event with Key.SHIFT and note that the shift key is down, and then listen for the Key.SHIFT released event and note that it's no longer down.
