### ISSUE TITLE
[bug] invokes toString on an array

### ISSUE THREAD

**Issue by waooog** [threerings/playn#84]
We find the following bug inside `playn/html`, the reason of this bug is the code converts an array (the return value of the method `soundController.getPreferredSoundTypes()` is an array) to a string directly, which will deliver the address of this array not the strings inside the array.

**Path**:  playn/html/src/playn/html/HtmlAudio.java 
**Bug location**: `soundController.getPreferredSoundTypes()` line 61

**Code**:
`
void init() {
HtmlPlatform.log.debug("Preferred sound type(s): " + soundController.getPreferredSoundTypes());
`

**Comment by samskivert** [comment]
I'm not sure what the concern is here. It's perfectly valid to convert a JavaScript array to a string. When the above code runs, it generates output like:

```
DEBUG: Preferred sound type(s): WEB_AUDIO,FLASH,HTML5
```
